package exceptionExamples;

public class Main {

    public static void main(String[] args) {
        Utils.doThis();
        System.out.println("And we're back in main!");
    }
    
}
